### ISSUE TITLE
Signup flow's Basic Information page "Read More" unresponsive

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#1]
STR: On the Basic Information page in the signup flow, click "Read more" button under the "Tell us about your level of activity" section
Observe nothing happens

Expected result is that clicking this button tells the user more about this question. or button should be removed. 

![unadjustednonraw_thumb_2](https://user-images.githubusercontent.com/43826887/47171129-be1c2400-d2bc-11e8-8b55-f5cc3352add5.jpg)

**Comment by munishbansal** [comment]
That is to be removed as confirmed by Mike
