### ISSUE TITLE
Logout screen has non responsive back button

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#13]
STR: When logged in as a user to the app click on the side nav
Click on log out
Observe screen they are taken to is the log in screen
Observe back button in upper left is not responsive

Expected result is that there is no back button if the user cannot go back, button should be removed

![unadjustednonraw_thumb_a](https://user-images.githubusercontent.com/43826887/47174558-c4fb6480-d2c5-11e8-9117-4045d29fc28b.jpg)

**Comment by munishbansal** [comment]
Ok. Part of the pending items list... closing it here
