### ISSUE TITLE
Meals order flow Address should be required

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#14]
STR: Begin a meal order and continue the flow to the Address page
Fill out only zipcode
Click continue
Observe that user is able to continue without an address

Expected result is that "Address" should be a required field

![unadjustednonraw_thumb_b](https://user-images.githubusercontent.com/43826887/47175020-16f0ba00-d2c7-11e8-833e-528be9f159d1.jpg)

**Comment by munishbansal** [comment]
Ok. I have copied it to pending items list and closing it here
