### ISSUE TITLE
Meals order flow "Order Summary" page delivery date is cut off

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#15]
STR: Begin a meal order and complete to the "Order Summary" page
Observe that delivery date information is cut off

Expected result is that delivery date information should not get cut off as the user needs this information

![unadjustednonraw_thumb_c](https://user-images.githubusercontent.com/43826887/47175249-8bc3f400-d2c7-11e8-9f29-8cab534eae98.jpg)

**Comment by munishbansal** [comment]
Should we reduce the gap between date ________ Oct

?

**Comment by sarahsboyer** [comment]
Either that or have the time window on a new line, whichever one makes it all fit

**Comment by sarahsboyer** [comment]
confirmed fixed
