### ISSUE TITLE
Recipes favoriting "unable to save" error

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#17]
STR: Be logged into the app as a user
Click on recipes tab
Click into a category, breakfast for example
Click on a recipe that has not been favorited by the user
Click on the open heart in the upper right
Observe heart turns solid
Click back button to return to list of recipes in category
Observe heart is not solid on the recipe

THEN
Click on open heart on recipe in the list
Observe error

OR
Click back into recipe
Observe heart is not solid anymore on recipe page
Click on heart
Observe error

Click all the way back out to "Macro Meals" recipe page
Click back into the category or into my favorites
Observe recipe is actually now favorited and shows a solid heart even though user just observed errors

Expected result is that when user favorites a recipe the heart turns solid for that recipe on all pages that it appears and stays that way without error messages

![unadjustednonraw_thumb_e](https://user-images.githubusercontent.com/43826887/47177311-f0358200-d2cc-11e8-9a05-f5f440427517.jpg)

**Comment by munishbansal** [comment]
sure

**Comment by munishbansal** [comment]
Fixed
