### ISSUE TITLE
Referring friends via email - no subject line

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#18]
STR: Logged into the app as a user, refer a friend
Select to refer via email
Send email
Observe email received to person being referred has no subject line

Expected result is that there is a subject line for the email sent

<img width="1021" alt="screen shot 2018-10-18 at 12 31 00 pm" src="https://user-images.githubusercontent.com/43826887/47179065-e9f5d480-d2d1-11e8-877b-168486a0529b.png">

**Comment by munishbansal** [comment]
only the body will be pre-populated
