### ISSUE TITLE
Meal Ordering Flow - if we already have their address we shouldn't ask for it again

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#19]
STR: Fully complete the meal order flow once including entering address
Complete a second order
Observed that user is asked for address again even though we have it
Expected result is that once we have the user's address we don't require them to enter it again, it should just have the option to view and edit in the confirmation page.

**Comment by munishbansal** [comment]
shall be fixed today. Backend changes has been done today to save the last
used address

**Comment by munishbansal** [comment]
fixed

**Comment by sarahsboyer** [comment]
I do see that we are pre-filling the address in the order flow now if we have it but I would propose we remove that screen if it is being pre-filled and only show it if we don't have an address.  The next screen that the user sees, the "Order summary" page shows the address and allows the user to edit it there.  So it's just an unnecessary page in the flow after the first order.

**Comment by simplifii** [comment]
Please confirm with Mike if we need to implement this. Its about 2-3 hours of work to make this change.
