### ISSUE TITLE
Signup flow activity level slider inaccurate number of ticks

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#2]
STR: In signup flow on Basic information page slide the activity level slider to the right
view that first few ticks are all unique activity levels and the last 2/3 of the ticks are all the same "super-active" level.

Expected result is that each tick should have a unique activity level, so they should be spaced further apart with fewer ticks to achieve this

![unadjustednonraw_thumb_2](https://user-images.githubusercontent.com/43826887/47171747-68487b80-d2be-11e8-8d39-6d7dfbb758b0.jpg)
in screenshot above - all the ticks to the right of where the slider is set are all the same, whereas the ticks to the left are all unique

**Comment by munishbansal** [comment]
This will be automatically fixed once the activity level data is added by you.
