### ISSUE TITLE
Un-Favorite recipe feature

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#20]
Currently the app has the ability to favorite a recipe but clicking on the heart again does nothing.

The user should be able to un-favorite a recipe that they favorited by clicking on the heart, the UI should return to the empty heart icon.

**Comment by munishbansal** [comment]
backend changes done to support the unfavorite function. Unfavorite
functionality shall be added during this week

**Comment by sarahsboyer** [comment]
verified as complete
