### ISSUE TITLE
Scrolling down on "Macro meals" page replaces My Favorites with another category

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#21]
STR: as a logged in user, go to the Macro Meals page of the app 
Observe first category is "My Favorites"
Scroll down to the bottom of the page and back up
Observe first category is now a duplicate "Entree" category - but clicking on this opens up "My Favorites" recipes

**Comment by munishbansal** [comment]
I am able to reproduce the issue. But its working fine on Chandresh's
iPhone. We will fix it when we sit together next

**Comment by sarahsboyer** [comment]
verified as fixed
