### ISSUE TITLE
Crash when viewing second recipe

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#25]
STR: As a logged in user go to the recipes part of the app
Click on a category
Click on a recipe
Click the back button
Click on another recipe
Observe crash

Expected result is that recipes can be viewed without crashing

**Comment by munishbansal** [comment]
Neither me nor Chandresh is able to reproduce this issue. Pls check again

**Comment by sarahsboyer** [comment]
@munishbansal and @csinghdev please see video shared in macrofit queries channel

**Comment by munishbansal** [comment]
Sarah, are u still facing this issue?

**Comment by sarahsboyer** [comment]
nope, verified fixed
