### ISSUE TITLE
Outside of delivery time window flow - screen flash

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#28]
STR: return to the app as a logged in user when it's outside of the ordering time window
observe there's a flash of the regular takeover screen and then the "sorry, delivery for this week is over" screen shows

Expected result is that there should be a smooth transition where the "sorry, delivery for this week is over" without flashing the other screen first.

**Comment by munishbansal** [comment]
There are pros and cons of this approach.

If this is very important then we can change but ideally it shouldn't be a
show stopper for V1.

**Comment by munishbansal** [comment]
Pls confirm if fixing this a must?
