### ISSUE TITLE
Outside of delivery time window flow - recipes page

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#29]
STR: Return to the app as a logged in user or complete the signup flow when outside of the delivery time window for the week
Observe that you're shown a full screen takeover (screenshot 1) alerting you that it's currently outside of the ordering/delivery window
Click "check out our recipes"
Observe that you're now taken to the recipe page which has been replaced by a slightly different version of the full takeover screen alerting you again that it's outside the ordering/delivery window again (screenshot 2) 
Since you're already on the recipes page you have to click elsewhere and then back to recipes to get the recipes to load

Expected result is that if the user clicks on "check out our recipes" on screenshot 1 they should be taken to the recipes page and shown the recipes, not shown another screen with the same warning.

![unadjustednonraw_thumb_17](https://user-images.githubusercontent.com/43826887/47519456-85db8f00-d842-11e8-8535-c2e5ff8eb3ac.jpg)

![unadjustednonraw_thumb_18](https://user-images.githubusercontent.com/43826887/47519586-adcaf280-d842-11e8-8e5a-eeea9be8bbc4.jpg)

**Comment by munishbansal** [comment]
Fixed... You can check the build that we are going to send today
