### ISSUE TITLE
Signup flow's Basic Information page "Read More about fitness goals" unresponsive

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#3]
STR: On the Basic Information page in the signup flow, click "Read More about fitness goals" button under the "Tell us about your fitness goals" section
Observe nothing happens

Expected result is that clicking this button tells the user more about this question. or button should be removed.

![unadjustednonraw_thumb_4](https://user-images.githubusercontent.com/43826887/47171979-05a3af80-d2bf-11e8-8f4a-26a9be26dba6.jpg)

**Comment by munishbansal** [comment]
That is to be removed as confirmed by Mike
