### ISSUE TITLE
Inches for height don't save.

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#32]
STR: Sign up as a user, type in a height that has inches, for example 5 foot 6 inches, and complete the signup flow
Click on settings and view that it now says the user is 5 foot 0 inches.

Expected behavior is that when the user enters some inches for their height, that the inches as well as the feet are saved and displayed.

**Comment by munishbansal** [comment]
Thanks. Its a bad miss.

We will fix this

**Comment by sarahsboyer** [comment]
verified fixed
