### ISSUE TITLE
Rating submits regardless of if the user clicks submit or not

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#34]
STR: as a logged in user click 5 stars on the home page
Click x on the pop up that asks you to submit
observe that rating is submitted anyway without clicking submit

Expected result is that if we ask the user to click submit, the submit action only happens if the user clicks submit.  Otherwise it should not submit.

**Comment by munishbansal** [comment]
If the user want us to give 5star feedback then why shouldn't we submit his
feedback as soon as he/she taps on star?

The Pop up that asks you to Submit

should actually lead you to app store page where the user can rate the app
on Apple App Store.

Please confirm.

**Comment by munishbansal** [comment]
we discussed this yesterday. 

Shouldn't we close this issue

**Comment by sarahsboyer** [comment]
If the submit pop up is just a placeholder for the app store and will be removed then yes this can be closed.
