### ISSUE TITLE
Signup flow back button on "Basic Information" page causes error

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#4]
STR: Complete the "Sign Up" page of the signup flow
Click continue
Click the back button in upper left
Observe that user is taken back to the "Sign Up" page they completed already
Click continue to attempt to complete the flow
Observe error message that doesn't allow user to complete the flow

Expected result is that we shouldn't let a user get into a state where they are stuck.  If the app is able to recognize it is still that same user who is trying to complete the flow it should let them continue, or probably the easier solution is to not allow the user to back track at that point.

![unadjustednonraw_thumb_5](https://user-images.githubusercontent.com/43826887/47172366-1ef92b80-d2c0-11e8-8d20-4389ff78b627.jpg)

**Comment by munishbansal** [comment]
Click the back button in upper left

We will rather not give the back button in Basic Details screen if the user is reaching that screen from signup screen

**Comment by munishbansal** [comment]
Fixed
