### ISSUE TITLE
Facebook signup - error when user doesn't share email address

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#48]
STR:

Click sign up with facebook
Log in to facebook account when prompted, select to not share email address
See errors in Macrofit app

Expected result is that if a field is required for the app to function, that we require that field from facebook.

![unadjustednonraw_thumb_2e](https://user-images.githubusercontent.com/43826887/49612099-7595f400-f958-11e8-9f20-f1d5b52b76eb.jpg)

![unadjustednonraw_thumb_2f](https://user-images.githubusercontent.com/43826887/49612088-7169d680-f958-11e8-9191-7daaa45f551f.jpg)

**Comment by munishbansal** [comment]
I think , If the user doesn’t give access to his email address then we
should take him to normal signup flow
