### ISSUE TITLE
Signup Flow "Set up your macros meal portions" custom percent doesn't highlight and is missing "%"

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#5]
STR: In the signup flow on the "Set up your macros meal portions" page click on the custom field for the "Macros for snacks?" selection 
Type in a number
Observe that box is not highlighted like the other boxes become highlighted when clicked on
Observe that number doesn't have a "%" behind it like the other boxes

Expected result is that the custom field should behave like the other fields and get a "%" appearing behind the number and highlight when clicked on.

![unadjustednonraw_thumb_6](https://user-images.githubusercontent.com/43826887/47172946-9bd8d500-d2c1-11e8-96a8-47585500616a.jpg)

**Comment by munishbansal** [comment]
Can we simply give 4 options:

0, 5, 10, 20 ?

**Comment by sarahsboyer** [comment]
That's up to @mikedeverna - is there a reason he wanted a custom field and how important is it?

**Comment by munishbansal** [comment]
Mike has given a go ahead on 4 static options: 0,5, 10, 20
