### ISSUE TITLE
Signup flow's Your Recommended Daily Macros page "Save to Photos" unresponsive

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#6]
STR: On the Your Recommended Daily Macros page in the signup flow, click "Save to Photos"
Observe nothing happens

Expected result is that clicking this button saves the macros per meal information to photos

![unadjustednonraw_thumb_7](https://user-images.githubusercontent.com/43826887/47173172-3afdcc80-d2c2-11e8-847c-4bd539b35a0f.jpg)

**Comment by munishbansal** [comment]
Yes. That's part of of the pending list and that's why I am close this bug
