### ISSUE TITLE
Signup flow "Select any dietary preferences" Settings button

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#8]
STR: In the Signup flow on the "Select any dietary preferences" page click the settings button in the upper right
Observe that the user is taken to a profile page that is blank even though the user has completed all this information
Observe that back button is unresponsive
User is required to fill out again all signup information to move forward

Expected result: we shouldn't let users get into a state where they are stuck or are asked to re-complete information. Settings button should be removed from this page

![unadjustednonraw_thumb_8](https://user-images.githubusercontent.com/43826887/47173531-22da7d00-d2c3-11e8-9aca-67c3ebe540e2.jpg)

**Comment by munishbansal** [comment]
Its covered in another issue
