### ISSUE TITLE
Signup flow "select any dietary preferences" special diet is required

### ISSUE THREAD

**Issue by sarahsboyer** [MacroFit/iOS#9]
STR: Complete the signup flow up until the "Select any dietary preferences" page
Observe that user cannot continue without selecting a dietary preference

Expected result is that dietary preferences aren't required - or there is a default "standard" option

![unadjustednonraw_thumb_8](https://user-images.githubusercontent.com/43826887/47173688-92e90300-d2c3-11e8-9f11-5cd926bcea41.jpg)

**Comment by munishbansal** [comment]
Its part of the pending items list and hence closing this issue

**Comment by sarahsboyer** [comment]
Thanks, can you share me on the pending items list?
